baseurl = "/"
languageCode = "en-US"
title = "Adaylin Alvarez"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "IMG_5945.jpg"
  author = "Adaylin Alvarez"
  occupation = "Biology and English major at the University of Texas at Austin"
  about = "I love all things books and plants, a perfect combination of both of my majors"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "adaylin1"
  Email         = "adaylin1@utexas.edu"
  LinkedIn      = "www.linkedin.com/in/adaylin-alvarez"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
